version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python main.py

workflows:
 build_and_test:
   jobs:
     - build
     - test:
       requires:
         - build